import { useNavigate, useParams } from "react-router-dom";
import { ChevronLeft } from "lucide-react";

const legalContent: Record<string, { title: string; content: string }> = {
  privacy: {
    title: "Privacy Policy",
    content: `Last updated: February 2026

FitNova ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, and share your personal information.

**Information We Collect**
• Personal information (name, email, age, gender, physical measurements)
• Fitness and health data (workout logs, food logs, progress data)
• Photos uploaded for food analysis
• Device information and usage analytics
• Subscription and payment information

**How We Use Your Data**
• To provide personalized AI-generated workout and diet plans
• To analyze food images for nutritional estimation
• To track your fitness progress
• To manage your subscription
• To improve our services

**Data Storage & Security**
All data is encrypted in transit and at rest. We use industry-standard security measures to protect your information. Your data is stored on secure cloud servers.

**Data Sharing**
We do not sell your personal data. We may share anonymized, aggregated data for analytics purposes. Food images are processed by AI services for nutritional analysis only.

**Your Rights**
You can request access to, correction of, or deletion of your personal data at any time through the app settings.

**Contact**
For privacy inquiries, contact us at privacy@fitnova.app`,
  },
  terms: {
    title: "Terms & Conditions",
    content: `Last updated: February 2026

By using FitNova, you agree to these Terms & Conditions.

**Service Description**
FitNova is an AI-powered fitness application that provides workout plans, diet plans, and food analysis. All AI-generated content is for informational purposes only.

**Subscriptions**
• Free tier includes limited features as described in the app
• Premium subscriptions are billed monthly or annually
• Subscriptions auto-renew unless cancelled at least 24 hours before the renewal date
• You can manage and cancel subscriptions through your device's app store settings
• No refunds for partial subscription periods

**User Responsibilities**
• You must be at least 18 years old to use FitNova
• You are responsible for maintaining the confidentiality of your account
• You agree to provide accurate information during registration

**Intellectual Property**
All content, features, and functionality of FitNova are owned by us and protected by copyright and other intellectual property laws.

**Limitation of Liability**
FitNova is provided "as is" without warranties. We are not liable for any damages arising from your use of the service.

**Termination**
We reserve the right to suspend or terminate your account for violation of these terms.`,
  },
  disclaimer: {
    title: "Medical Disclaimer",
    content: `**Important: Please Read Carefully**

FitNova is a fitness and nutrition informational tool. It is NOT a substitute for professional medical advice, diagnosis, or treatment.

**AI-Generated Content**
• All workout plans, diet plans, and nutritional analyses are generated by artificial intelligence
• AI estimations may vary in accuracy and should not be relied upon as precise measurements
• Food nutritional values from image scanning are estimates only

**Health Warnings**
• Always consult with a qualified healthcare professional before starting any new exercise program or diet plan
• If you experience pain, dizziness, or discomfort during exercise, stop immediately and seek medical attention
• This app does not diagnose, treat, cure, or prevent any disease or medical condition

**Not Medical Advice**
• The information provided by FitNova should not be considered medical or nutritional advice
• We are not licensed healthcare providers
• Individual results may vary

**Assumption of Risk**
By using FitNova, you acknowledge that physical exercise involves inherent risks and you voluntarily assume all risks associated with the use of this application.

**Emergency**
If you are experiencing a medical emergency, call your local emergency services immediately. Do not rely on this app for medical guidance.`,
  },
};

const Legal = () => {
  const navigate = useNavigate();
  const { type } = useParams<{ type: string }>();
  const page = legalContent[type || "privacy"];

  if (!page) return null;

  return (
    <div className="min-h-screen bg-background safe-top">
      <div className="px-6 pt-6 pb-8">
        <div className="flex items-center gap-3 mb-6">
          <button onClick={() => navigate(-1)} className="w-10 h-10 rounded-xl bg-secondary flex items-center justify-center">
            <ChevronLeft className="w-5 h-5 text-foreground" />
          </button>
          <h1 className="font-display text-xl font-bold text-foreground">{page.title}</h1>
        </div>

        <div className="prose prose-invert prose-sm max-w-none">
          {page.content.split("\n\n").map((paragraph, idx) => {
            if (paragraph.startsWith("**") && paragraph.endsWith("**")) {
              return <h3 key={idx} className="text-base font-semibold text-foreground mt-6 mb-2">{paragraph.replace(/\*\*/g, "")}</h3>;
            }
            if (paragraph.includes("**")) {
              const parts = paragraph.split("**");
              return (
                <div key={idx} className="mb-3">
                  {parts.map((part, i) =>
                    i % 2 === 1
                      ? <strong key={i} className="text-foreground font-semibold">{part}</strong>
                      : <span key={i} className="text-muted-foreground text-sm leading-relaxed">{part}</span>
                  )}
                </div>
              );
            }
            if (paragraph.startsWith("•")) {
              return (
                <ul key={idx} className="space-y-1 mb-3">
                  {paragraph.split("\n").map((item, i) => (
                    <li key={i} className="text-sm text-muted-foreground leading-relaxed pl-2">
                      {item}
                    </li>
                  ))}
                </ul>
              );
            }
            return <p key={idx} className="text-sm text-muted-foreground leading-relaxed mb-3">{paragraph}</p>;
          })}
        </div>
      </div>
    </div>
  );
};

export default Legal;
